// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/mightyK1ngRichard",
            "email": "dimapermyakov55@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notification": {
            "post": {
                "description": "Добавляет новое уведомление.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Уведомления"
                ],
                "summary": "Добавление уведомления",
                "parameters": [
                    {
                        "description": "Информация об уведомлении",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddNotificationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Уведомление успешно добавлено",
                        "schema": {
                            "$ref": "#/definitions/model.AddNotificationRes"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос. Проверьте корректность данных уведомления.",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResp"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResp"
                        }
                    }
                }
            }
        },
        "/notification/{id}": {
            "delete": {
                "description": "Меняем статус уведомления на прочитано",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Уведомления"
                ],
                "summary": "Удаление уведомления",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID уведомления",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Уведомление прочитано",
                        "schema": {
                            "$ref": "#/definitions/model.DeleteNotificationRes"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResp"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.errorResp": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Описание ошибки"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.AddNotificationReq": {
            "type": "object",
            "properties": {
                "sellerID": {
                    "type": "integer"
                },
                "text": {
                    "type": "string",
                    "example": "Текст"
                },
                "title": {
                    "type": "string",
                    "example": "Заголовок"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "model.AddNotificationRes": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.DeleteNotificationRes": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.1.37:6070",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "CakesHub",
	Description:      "Маркетплейс по продаже тортов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
